// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=ts"
// @generated from file common.proto (package jlucraft.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SEmpsdWNyYWZ0LmNvbW1vbi52MSIHCgVFbXB0eSKPAQoFRXJyb3ISDAoEY29kZRgBIAEoCRIPCgdtZXNzYWdlGAIgASgJEjcKB2RldGFpbHMYAyADKAsyJi5qbHVjcmFmdC5jb21tb24udjEuRXJyb3IuRGV0YWlsc0VudHJ5Gi4KDERldGFpbHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIiwKC1BhZ2VSZXF1ZXN0Eg0KBWxpbWl0GAEgASgNEg4KBmN1cnNvchgCIAEoCSIxCghQYWdlSW5mbxITCgtuZXh0X2N1cnNvchgBIAEoCRIQCghoYXNfbW9yZRgCIAEoCCJICg9SZXNvdXJjZVJlcXVlc3QSEQoJY3B1X2NvcmVzGAEgASgNEhEKCW1lbW9yeV9nYhgCIAEoBBIPCgdkaXNrX2diGAMgASgEIk4KDFBlZXJJZGVudGl0eRIPCgdwZWVyX2lkGAEgASgJEhIKCnB1YmxpY19rZXkYAiABKAkSCwoDZGlkGAMgASgJEgwKBGNsdWIYBCABKAkiRwoNU2lnbmVkUmVxdWVzdBINCgVub25jZRgBIAEoCRIRCglzaWduYXR1cmUYAiABKAkSFAoMY2hhbGxlbmdlX2lkGAMgASgJInQKC0F1dGhDb250ZXh0Ei8KBWFjdG9yGAEgASgLMiAuamx1Y3JhZnQuY29tbW9uLnYxLlBlZXJJZGVudGl0eRI0CglzaWduYXR1cmUYAiABKAsyIS5qbHVjcmFmdC5jb21tb24udjEuU2lnbmVkUmVxdWVzdCInCglUaW1lUmFuZ2USDQoFc3RhcnQYASABKAkSCwoDZW5kGAIgASgJIhwKClN0cmluZ0xpc3QSDgoGdmFsdWVzGAEgAygJIiYKCEtleVZhbHVlEgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCSI2Cg1CeXRlc0VudmVsb3BlEhQKDGNvbnRlbnRfdHlwZRgBIAEoCRIPCgdwYXlsb2FkGAIgASgMQhoKFmNvbS5qbHVjcmFmdC5jb21tb24udjFQAWIGcHJvdG8z");

/**
 * @generated from message jlucraft.common.v1.Empty
 */
export type Empty = Message<"jlucraft.common.v1.Empty"> & {
};

/**
 * Describes the message jlucraft.common.v1.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * @generated from message jlucraft.common.v1.Error
 */
export type Error = Message<"jlucraft.common.v1.Error"> & {
  /**
   * @generated from field: string code = 1;
   */
  code: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: map<string, string> details = 3;
   */
  details: { [key: string]: string };
};

/**
 * Describes the message jlucraft.common.v1.Error.
 * Use `create(ErrorSchema)` to create a new message.
 */
export const ErrorSchema: GenMessage<Error> = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * @generated from message jlucraft.common.v1.PageRequest
 */
export type PageRequest = Message<"jlucraft.common.v1.PageRequest"> & {
  /**
   * @generated from field: uint32 limit = 1;
   */
  limit: number;

  /**
   * @generated from field: string cursor = 2;
   */
  cursor: string;
};

/**
 * Describes the message jlucraft.common.v1.PageRequest.
 * Use `create(PageRequestSchema)` to create a new message.
 */
export const PageRequestSchema: GenMessage<PageRequest> = /*@__PURE__*/
  messageDesc(file_common, 2);

/**
 * @generated from message jlucraft.common.v1.PageInfo
 */
export type PageInfo = Message<"jlucraft.common.v1.PageInfo"> & {
  /**
   * @generated from field: string next_cursor = 1;
   */
  nextCursor: string;

  /**
   * @generated from field: bool has_more = 2;
   */
  hasMore: boolean;
};

/**
 * Describes the message jlucraft.common.v1.PageInfo.
 * Use `create(PageInfoSchema)` to create a new message.
 */
export const PageInfoSchema: GenMessage<PageInfo> = /*@__PURE__*/
  messageDesc(file_common, 3);

/**
 * @generated from message jlucraft.common.v1.ResourceRequest
 */
export type ResourceRequest = Message<"jlucraft.common.v1.ResourceRequest"> & {
  /**
   * @generated from field: uint32 cpu_cores = 1;
   */
  cpuCores: number;

  /**
   * @generated from field: uint64 memory_gb = 2;
   */
  memoryGb: bigint;

  /**
   * @generated from field: uint64 disk_gb = 3;
   */
  diskGb: bigint;
};

/**
 * Describes the message jlucraft.common.v1.ResourceRequest.
 * Use `create(ResourceRequestSchema)` to create a new message.
 */
export const ResourceRequestSchema: GenMessage<ResourceRequest> = /*@__PURE__*/
  messageDesc(file_common, 4);

/**
 * @generated from message jlucraft.common.v1.PeerIdentity
 */
export type PeerIdentity = Message<"jlucraft.common.v1.PeerIdentity"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;

  /**
   * @generated from field: string public_key = 2;
   */
  publicKey: string;

  /**
   * @generated from field: string did = 3;
   */
  did: string;

  /**
   * @generated from field: string club = 4;
   */
  club: string;
};

/**
 * Describes the message jlucraft.common.v1.PeerIdentity.
 * Use `create(PeerIdentitySchema)` to create a new message.
 */
export const PeerIdentitySchema: GenMessage<PeerIdentity> = /*@__PURE__*/
  messageDesc(file_common, 5);

/**
 * @generated from message jlucraft.common.v1.SignedRequest
 */
export type SignedRequest = Message<"jlucraft.common.v1.SignedRequest"> & {
  /**
   * @generated from field: string nonce = 1;
   */
  nonce: string;

  /**
   * @generated from field: string signature = 2;
   */
  signature: string;

  /**
   * @generated from field: string challenge_id = 3;
   */
  challengeId: string;
};

/**
 * Describes the message jlucraft.common.v1.SignedRequest.
 * Use `create(SignedRequestSchema)` to create a new message.
 */
export const SignedRequestSchema: GenMessage<SignedRequest> = /*@__PURE__*/
  messageDesc(file_common, 6);

/**
 * @generated from message jlucraft.common.v1.AuthContext
 */
export type AuthContext = Message<"jlucraft.common.v1.AuthContext"> & {
  /**
   * @generated from field: jlucraft.common.v1.PeerIdentity actor = 1;
   */
  actor?: PeerIdentity | undefined;

  /**
   * @generated from field: jlucraft.common.v1.SignedRequest signature = 2;
   */
  signature?: SignedRequest | undefined;
};

/**
 * Describes the message jlucraft.common.v1.AuthContext.
 * Use `create(AuthContextSchema)` to create a new message.
 */
export const AuthContextSchema: GenMessage<AuthContext> = /*@__PURE__*/
  messageDesc(file_common, 7);

/**
 * @generated from message jlucraft.common.v1.TimeRange
 */
export type TimeRange = Message<"jlucraft.common.v1.TimeRange"> & {
  /**
   * @generated from field: string start = 1;
   */
  start: string;

  /**
   * @generated from field: string end = 2;
   */
  end: string;
};

/**
 * Describes the message jlucraft.common.v1.TimeRange.
 * Use `create(TimeRangeSchema)` to create a new message.
 */
export const TimeRangeSchema: GenMessage<TimeRange> = /*@__PURE__*/
  messageDesc(file_common, 8);

/**
 * @generated from message jlucraft.common.v1.StringList
 */
export type StringList = Message<"jlucraft.common.v1.StringList"> & {
  /**
   * @generated from field: repeated string values = 1;
   */
  values: string[];
};

/**
 * Describes the message jlucraft.common.v1.StringList.
 * Use `create(StringListSchema)` to create a new message.
 */
export const StringListSchema: GenMessage<StringList> = /*@__PURE__*/
  messageDesc(file_common, 9);

/**
 * @generated from message jlucraft.common.v1.KeyValue
 */
export type KeyValue = Message<"jlucraft.common.v1.KeyValue"> & {
  /**
   * @generated from field: string key = 1;
   */
  key: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message jlucraft.common.v1.KeyValue.
 * Use `create(KeyValueSchema)` to create a new message.
 */
export const KeyValueSchema: GenMessage<KeyValue> = /*@__PURE__*/
  messageDesc(file_common, 10);

/**
 * @generated from message jlucraft.common.v1.BytesEnvelope
 */
export type BytesEnvelope = Message<"jlucraft.common.v1.BytesEnvelope"> & {
  /**
   * @generated from field: string content_type = 1;
   */
  contentType: string;

  /**
   * @generated from field: bytes payload = 2;
   */
  payload: Uint8Array;
};

/**
 * Describes the message jlucraft.common.v1.BytesEnvelope.
 * Use `create(BytesEnvelopeSchema)` to create a new message.
 */
export const BytesEnvelopeSchema: GenMessage<BytesEnvelope> = /*@__PURE__*/
  messageDesc(file_common, 11);

