// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=ts"
// @generated from file records.proto (package jlucraft.records.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file records.proto.
 */
export const file_records: GenFile = /*@__PURE__*/
  fileDesc("Cg1yZWNvcmRzLnByb3RvEhNqbHVjcmFmdC5yZWNvcmRzLnYxIukBCgpSZXNvdXJjZUFkEg8KB3BlZXJfaWQYASABKAkSEgoKbXVsdGlhZGRycxgCIAMoCRIVCg1hdmFpbGFibGVfY3B1GAMgASgCEhsKE2F2YWlsYWJsZV9tZW1vcnlfbWIYBCABKAQSGQoRYXZhaWxhYmxlX2Rpc2tfbWIYBSABKAQSGAoQYWN0aXZlX2luc3RhbmNlcxgGIAEoDRISCgpub2RlX3Njb3JlGAcgASgBEhIKCnVwZGF0ZWRfYXQYCCABKAkSEgoKcHVibGljX2tleRgJIAEoDBIRCglzaWduYXR1cmUYCiABKAwiywEKDkluc3RhbmNlUmVjb3JkEhMKC2luc3RhbmNlX2lkGAEgASgJEg8KB3BlZXJfaWQYAiABKAkSFAoMbGlzdGVuX2FkZHJzGAMgAygJEhQKDHB1Ymxpc2hlZF9hdBgEIAEoCRISCgpwdWJsaWNfa2V5GAUgASgMEhEKCXNpZ25hdHVyZRgGIAEoDBIaCg1wcm94eV9hZGRyZXNzGAcgASgJSACIAQESEgoKcHVibGljX2lwcxgIIAMoCUIQCg5fcHJveHlfYWRkcmVzcyKOBAoQTm9kZUFubm91bmNlbWVudBIPCgdwZWVyX2lkGAEgASgJEg4KBnN0YXR1cxgCIAEoCRISCgp1cGRhdGVkX2F0GAMgASgJEhgKEGFjY2VwdF93b3JrbG9hZHMYBCABKAgSFQoNcHJvdmlkZV9yZWxheRgFIAEoCBIdChVleHBvc2VfcHVibGljX2luZ3Jlc3MYBiABKAgSQQoGbGFiZWxzGAcgAygLMjEuamx1Y3JhZnQucmVjb3Jkcy52MS5Ob2RlQW5ub3VuY2VtZW50LkxhYmVsc0VudHJ5EhQKDGxpc3Rlbl9hZGRycxgIIAMoCRISCgpwdWJsaWNfaXBzGAkgAygJEhYKDmluc3RhbmNlX2NvdW50GAogASgEEhkKEXJ1bm5pbmdfaW5zdGFuY2VzGAsgASgEEhYKDmNvbnNlbnN1c19yb2xlGAwgASgJEhoKEm9yYWNsZV9yZXBvcnRfZGF0ZRgNIAEoCRIeChFwcm94eV9saXN0ZW5fYWRkchgOIAEoCUgAiAEBEiIKFXlnZ2RyYXNpbF9saXN0ZW5fYWRkchgPIAEoCUgBiAEBGi0KC0xhYmVsc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAFCFAoSX3Byb3h5X2xpc3Rlbl9hZGRyQhgKFl95Z2dkcmFzaWxfbGlzdGVuX2FkZHIixQEKC0pvaW5SZXF1ZXN0Eg8KB3BlZXJfaWQYASABKAkSEgoKcHVibGljX2tleRgCIAEoDBI8CgZsYWJlbHMYAyADKAsyLC5qbHVjcmFmdC5yZWNvcmRzLnYxLkpvaW5SZXF1ZXN0LkxhYmVsc0VudHJ5EhEKCXRpbWVzdGFtcBgEIAEoCRIRCglzaWduYXR1cmUYBSABKAwaLQoLTGFiZWxzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUIbChdjb20uamx1Y3JhZnQucmVjb3Jkcy52MVABYgZwcm90bzM");

/**
 * @generated from message jlucraft.records.v1.ResourceAd
 */
export type ResourceAd = Message<"jlucraft.records.v1.ResourceAd"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;

  /**
   * @generated from field: repeated string multiaddrs = 2;
   */
  multiaddrs: string[];

  /**
   * @generated from field: float available_cpu = 3;
   */
  availableCpu: number;

  /**
   * @generated from field: uint64 available_memory_mb = 4;
   */
  availableMemoryMb: bigint;

  /**
   * @generated from field: uint64 available_disk_mb = 5;
   */
  availableDiskMb: bigint;

  /**
   * @generated from field: uint32 active_instances = 6;
   */
  activeInstances: number;

  /**
   * @generated from field: double node_score = 7;
   */
  nodeScore: number;

  /**
   * @generated from field: string updated_at = 8;
   */
  updatedAt: string;

  /**
   * @generated from field: bytes public_key = 9;
   */
  publicKey: Uint8Array;

  /**
   * @generated from field: bytes signature = 10;
   */
  signature: Uint8Array;
};

/**
 * Describes the message jlucraft.records.v1.ResourceAd.
 * Use `create(ResourceAdSchema)` to create a new message.
 */
export const ResourceAdSchema: GenMessage<ResourceAd> = /*@__PURE__*/
  messageDesc(file_records, 0);

/**
 * @generated from message jlucraft.records.v1.InstanceRecord
 */
export type InstanceRecord = Message<"jlucraft.records.v1.InstanceRecord"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;

  /**
   * @generated from field: string peer_id = 2;
   */
  peerId: string;

  /**
   * @generated from field: repeated string listen_addrs = 3;
   */
  listenAddrs: string[];

  /**
   * @generated from field: string published_at = 4;
   */
  publishedAt: string;

  /**
   * @generated from field: bytes public_key = 5;
   */
  publicKey: Uint8Array;

  /**
   * @generated from field: bytes signature = 6;
   */
  signature: Uint8Array;

  /**
   * @generated from field: optional string proxy_address = 7;
   */
  proxyAddress?: string | undefined;

  /**
   * @generated from field: repeated string public_ips = 8;
   */
  publicIps: string[];
};

/**
 * Describes the message jlucraft.records.v1.InstanceRecord.
 * Use `create(InstanceRecordSchema)` to create a new message.
 */
export const InstanceRecordSchema: GenMessage<InstanceRecord> = /*@__PURE__*/
  messageDesc(file_records, 1);

/**
 * @generated from message jlucraft.records.v1.NodeAnnouncement
 */
export type NodeAnnouncement = Message<"jlucraft.records.v1.NodeAnnouncement"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;

  /**
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * @generated from field: string updated_at = 3;
   */
  updatedAt: string;

  /**
   * @generated from field: bool accept_workloads = 4;
   */
  acceptWorkloads: boolean;

  /**
   * @generated from field: bool provide_relay = 5;
   */
  provideRelay: boolean;

  /**
   * @generated from field: bool expose_public_ingress = 6;
   */
  exposePublicIngress: boolean;

  /**
   * @generated from field: map<string, string> labels = 7;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: repeated string listen_addrs = 8;
   */
  listenAddrs: string[];

  /**
   * @generated from field: repeated string public_ips = 9;
   */
  publicIps: string[];

  /**
   * @generated from field: uint64 instance_count = 10;
   */
  instanceCount: bigint;

  /**
   * @generated from field: uint64 running_instances = 11;
   */
  runningInstances: bigint;

  /**
   * @generated from field: string consensus_role = 12;
   */
  consensusRole: string;

  /**
   * @generated from field: string oracle_report_date = 13;
   */
  oracleReportDate: string;

  /**
   * @generated from field: optional string proxy_listen_addr = 14;
   */
  proxyListenAddr?: string | undefined;

  /**
   * @generated from field: optional string yggdrasil_listen_addr = 15;
   */
  yggdrasilListenAddr?: string | undefined;
};

/**
 * Describes the message jlucraft.records.v1.NodeAnnouncement.
 * Use `create(NodeAnnouncementSchema)` to create a new message.
 */
export const NodeAnnouncementSchema: GenMessage<NodeAnnouncement> = /*@__PURE__*/
  messageDesc(file_records, 2);

/**
 * @generated from message jlucraft.records.v1.JoinRequest
 */
export type JoinRequest = Message<"jlucraft.records.v1.JoinRequest"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;

  /**
   * @generated from field: bytes public_key = 2;
   */
  publicKey: Uint8Array;

  /**
   * @generated from field: map<string, string> labels = 3;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: string timestamp = 4;
   */
  timestamp: string;

  /**
   * @generated from field: bytes signature = 5;
   */
  signature: Uint8Array;
};

/**
 * Describes the message jlucraft.records.v1.JoinRequest.
 * Use `create(JoinRequestSchema)` to create a new message.
 */
export const JoinRequestSchema: GenMessage<JoinRequest> = /*@__PURE__*/
  messageDesc(file_records, 3);

