// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=ts"
// @generated from file resources.proto (package jlucraft.resources.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file resources.proto.
 */
export const file_resources: GenFile = /*@__PURE__*/
  fileDesc("Cg9yZXNvdXJjZXMucHJvdG8SFWpsdWNyYWZ0LnJlc291cmNlcy52MSJsChBSZXNvdXJjZU1hbmlmZXN0Eg8KB3ZlcnNpb24YASABKA0SEwoLaW5zdGFuY2VfaWQYAiABKAkSMgoFZmlsZXMYAyADKAsyIy5qbHVjcmFmdC5yZXNvdXJjZXMudjEuTWFuaWZlc3RGaWxlIoABCgxNYW5pZmVzdEZpbGUSDAoEcGF0aBgBIAEoCRIMCgRoYXNoGAIgASgJEgwKBHNpemUYAyABKAQSEAoIcmVxdWlyZWQYBCABKAgSNAoGY2h1bmtzGAUgAygLMiQuamx1Y3JhZnQucmVzb3VyY2VzLnYxLk1hbmlmZXN0Q2h1bmsiSgoNTWFuaWZlc3RDaHVuaxINCgVpbmRleBgBIAEoDRIOCgZvZmZzZXQYAiABKAQSDAoEc2l6ZRgDIAEoBBIMCgRoYXNoGAQgASgJIjcKDENodW5rUmVxdWVzdBISCgpjaHVua19oYXNoGAEgASgJEhMKC2luc3RhbmNlX2lkGAIgASgJIk4KDUNodW5rUmVzcG9uc2USEgoKY2h1bmtfaGFzaBgBIAEoCRIMCgRzaXplGAIgASgEEgwKBGRhdGEYAyABKAwSDQoFZXJyb3IYBCABKAkieAoSUmVzb3VyY2VQcm92aWRlckFkEg8KB3BlZXJfaWQYASABKAkSFAoMY2h1bmtfaGFzaGVzGAIgAygJEhQKDHB1Ymxpc2hlZF9hdBgDIAEoCRISCgpwdWJsaWNfa2V5GAQgASgMEhEKCXNpZ25hdHVyZRgFIAEoDCJaCgpDYWNoZUVudHJ5EgwKBGhhc2gYASABKAkSDAoEc2l6ZRgCIAEoBBIYChBsYXN0X2FjY2Vzc2VkX2F0GAMgASgJEhYKDmludGVncml0eV9oYXNoGAQgASgJIlgKDkNhY2hlSW52ZW50b3J5EjIKB2VudHJpZXMYASADKAsyIS5qbHVjcmFmdC5yZXNvdXJjZXMudjEuQ2FjaGVFbnRyeRISCgp0b3RhbF9zaXplGAIgASgEQh0KGWNvbS5qbHVjcmFmdC5yZXNvdXJjZXMudjFQAWIGcHJvdG8z");

/**
 * @generated from message jlucraft.resources.v1.ResourceManifest
 */
export type ResourceManifest = Message<"jlucraft.resources.v1.ResourceManifest"> & {
  /**
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from field: string instance_id = 2;
   */
  instanceId: string;

  /**
   * @generated from field: repeated jlucraft.resources.v1.ManifestFile files = 3;
   */
  files: ManifestFile[];
};

/**
 * Describes the message jlucraft.resources.v1.ResourceManifest.
 * Use `create(ResourceManifestSchema)` to create a new message.
 */
export const ResourceManifestSchema: GenMessage<ResourceManifest> = /*@__PURE__*/
  messageDesc(file_resources, 0);

/**
 * @generated from message jlucraft.resources.v1.ManifestFile
 */
export type ManifestFile = Message<"jlucraft.resources.v1.ManifestFile"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * @generated from field: string hash = 2;
   */
  hash: string;

  /**
   * @generated from field: uint64 size = 3;
   */
  size: bigint;

  /**
   * @generated from field: bool required = 4;
   */
  required: boolean;

  /**
   * @generated from field: repeated jlucraft.resources.v1.ManifestChunk chunks = 5;
   */
  chunks: ManifestChunk[];
};

/**
 * Describes the message jlucraft.resources.v1.ManifestFile.
 * Use `create(ManifestFileSchema)` to create a new message.
 */
export const ManifestFileSchema: GenMessage<ManifestFile> = /*@__PURE__*/
  messageDesc(file_resources, 1);

/**
 * @generated from message jlucraft.resources.v1.ManifestChunk
 */
export type ManifestChunk = Message<"jlucraft.resources.v1.ManifestChunk"> & {
  /**
   * @generated from field: uint32 index = 1;
   */
  index: number;

  /**
   * @generated from field: uint64 offset = 2;
   */
  offset: bigint;

  /**
   * @generated from field: uint64 size = 3;
   */
  size: bigint;

  /**
   * @generated from field: string hash = 4;
   */
  hash: string;
};

/**
 * Describes the message jlucraft.resources.v1.ManifestChunk.
 * Use `create(ManifestChunkSchema)` to create a new message.
 */
export const ManifestChunkSchema: GenMessage<ManifestChunk> = /*@__PURE__*/
  messageDesc(file_resources, 2);

/**
 * @generated from message jlucraft.resources.v1.ChunkRequest
 */
export type ChunkRequest = Message<"jlucraft.resources.v1.ChunkRequest"> & {
  /**
   * @generated from field: string chunk_hash = 1;
   */
  chunkHash: string;

  /**
   * @generated from field: string instance_id = 2;
   */
  instanceId: string;
};

/**
 * Describes the message jlucraft.resources.v1.ChunkRequest.
 * Use `create(ChunkRequestSchema)` to create a new message.
 */
export const ChunkRequestSchema: GenMessage<ChunkRequest> = /*@__PURE__*/
  messageDesc(file_resources, 3);

/**
 * @generated from message jlucraft.resources.v1.ChunkResponse
 */
export type ChunkResponse = Message<"jlucraft.resources.v1.ChunkResponse"> & {
  /**
   * @generated from field: string chunk_hash = 1;
   */
  chunkHash: string;

  /**
   * @generated from field: uint64 size = 2;
   */
  size: bigint;

  /**
   * @generated from field: bytes data = 3;
   */
  data: Uint8Array;

  /**
   * @generated from field: string error = 4;
   */
  error: string;
};

/**
 * Describes the message jlucraft.resources.v1.ChunkResponse.
 * Use `create(ChunkResponseSchema)` to create a new message.
 */
export const ChunkResponseSchema: GenMessage<ChunkResponse> = /*@__PURE__*/
  messageDesc(file_resources, 4);

/**
 * @generated from message jlucraft.resources.v1.ResourceProviderAd
 */
export type ResourceProviderAd = Message<"jlucraft.resources.v1.ResourceProviderAd"> & {
  /**
   * @generated from field: string peer_id = 1;
   */
  peerId: string;

  /**
   * @generated from field: repeated string chunk_hashes = 2;
   */
  chunkHashes: string[];

  /**
   * @generated from field: string published_at = 3;
   */
  publishedAt: string;

  /**
   * @generated from field: bytes public_key = 4;
   */
  publicKey: Uint8Array;

  /**
   * @generated from field: bytes signature = 5;
   */
  signature: Uint8Array;
};

/**
 * Describes the message jlucraft.resources.v1.ResourceProviderAd.
 * Use `create(ResourceProviderAdSchema)` to create a new message.
 */
export const ResourceProviderAdSchema: GenMessage<ResourceProviderAd> = /*@__PURE__*/
  messageDesc(file_resources, 5);

/**
 * @generated from message jlucraft.resources.v1.CacheEntry
 */
export type CacheEntry = Message<"jlucraft.resources.v1.CacheEntry"> & {
  /**
   * @generated from field: string hash = 1;
   */
  hash: string;

  /**
   * @generated from field: uint64 size = 2;
   */
  size: bigint;

  /**
   * @generated from field: string last_accessed_at = 3;
   */
  lastAccessedAt: string;

  /**
   * @generated from field: string integrity_hash = 4;
   */
  integrityHash: string;
};

/**
 * Describes the message jlucraft.resources.v1.CacheEntry.
 * Use `create(CacheEntrySchema)` to create a new message.
 */
export const CacheEntrySchema: GenMessage<CacheEntry> = /*@__PURE__*/
  messageDesc(file_resources, 6);

/**
 * @generated from message jlucraft.resources.v1.CacheInventory
 */
export type CacheInventory = Message<"jlucraft.resources.v1.CacheInventory"> & {
  /**
   * @generated from field: repeated jlucraft.resources.v1.CacheEntry entries = 1;
   */
  entries: CacheEntry[];

  /**
   * @generated from field: uint64 total_size = 2;
   */
  totalSize: bigint;
};

/**
 * Describes the message jlucraft.resources.v1.CacheInventory.
 * Use `create(CacheInventorySchema)` to create a new message.
 */
export const CacheInventorySchema: GenMessage<CacheInventory> = /*@__PURE__*/
  messageDesc(file_resources, 7);

